shire:
	@sudo echo "\n127.0.0.1\txiaomo.douban.com\n" \
			   "127.0.0.1\t9.xiaomo.douban.com\n" \
			   "127.0.0.1\tbook.xiaomo.douban.com\n" \
			   "127.0.0.1\tmovie.xiaomo.douban.com\n" \
			   "127.0.0.1\tmusic.xiaomo.douban.com\n" >> /etc/hosts
