homebrew:
	echo "Install Homebrew"
	ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
	brew doctor

packages:
	echo "Install Packages"
	brew install ack ctags cmake tmux tree node nmap ncdu
